#!/usr/bin/expect -f

### Prompt User for password and save to local variable ###
stty -echo
send_user -- "Enter CAEN login password "
expect_user -re "(.*)\n"
send_user "\r"
stty echo
set pass $expect_out(0, string)

### Spawn ssh session ###
spawn ssh schulteb@login.engin.umich.edu
set timeout 2

### Sometimes CAEN will timeout and script will hang ###
expect  {
    "word: " { send "$pass\r" }
    timeout { interact } 
}

set timeout 10

### Send DUO push option ###
expect  {
    "Passcode or option (1-3): " { send -- "1\r" }
    timeout { exit 1 }
}

interact
